name: "workflow to deploy a sonarqube server into aws"

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'what action would you like to do?'
        required: true
        type: choice
        options:
          - 'deploy'
          - 'destroy'
  # push:
  #   paths-ignore:
  #     - '.github/**'
  #     - '.gitignore'
  #     - 'README.md'
  #   branches:
  #     - main

jobs:
  call-deploy-workflow:
    if: ${{ github.event.inputs.action == 'deploy' }}
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  call-destroy-workflow:
    if: ${{ github.event.inputs.action == 'destroy' }}
    uses: ./.github/workflows/destroy.yml
    secrets: inherit